// auth
export const EMAIL_REGISTER_PENDING = "EMAIL_REGISTER_PENDING";
export const EMAIL_REGISTER_SUCCESS = "EMAIL_REGISTER_SUCCESS";
export const EMAIL_REGISTER_ERROR = "EMAIL_REGISTER_ERROR";

export const EMAIL_LOGIN_PENDING = "EMAIL_LOGIN_PENDING";
export const EMAIL_LOGIN_SUCCESS = "EMAIL_LOGIN_SUCCESS";
export const EMAIL_LOGIN_ERROR = "EMAIL_LOGIN_ERROR";

export const GOOGLE_LOGIN_PENDING = "GOOGLE_LOGIN_PENDING";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_ERROR = "GOOGLE_LOGIN_ERROR";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

// product
export const GET_PRODUCT_LIST_PENDING = "GET_PRODUCT_LIST_PENDING";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_ERROR = "GET_PRODUCT_LIST_ERROR";

export const GET_PRODUCT_DETAIL_PENDING = "GET_PRODUCT_DETAIL_PENDING";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_PRODUCT_DETAIL_ERROR = "GET_PRODUCT_DETAIL_ERROR";

// cart
export const INSERT_CART_PENDING = "INSERT_CART_PENDING";
export const INSERT_CART_SUCCESS = "INSERT_CART_SUCCESS";
export const INSERT_CART_ERROR = "INSERT_CART_ERROR";

export const GET_CART_PENDING = "GET_CART_PENDING";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";

export const UPDATE_CART_PENDING = "UPDATE_CART_PENDING";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_ERROR = "UPDATE_CART_ERROR";

export const REMOVE_CART_PENDING = "REMOVE_CART_PENDING";
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";
export const REMOVE_CART_ERROR = "REMOVE_CART_ERROR";
