export const EMAIL_REGISTER_PENDING = "EMAIL_REGISTER_PENDING";
export const EMAIL_REGISTER_SUCCESS = "EMAIL_REGISTER_SUCCESS";
export const EMAIL_REGISTER_ERROR = "EMAIL_REGISTER_ERROR";

export const EMAIL_LOGIN_PENDING = "EMAIL_LOGIN_PENDING";
export const EMAIL_LOGIN_SUCCESS = "EMAIL_LOGIN_SUCCESS";
export const EMAIL_LOGIN_ERROR = "EMAIL_LOGIN_ERROR";

export const GOOGLE_LOGIN_PENDING = "GOOGLE_LOGIN_PENDING";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_ERROR = "GOOGLE_LOGIN_ERROR";
