// auth
export const EMAIL_REGISTER_PENDING = "EMAIL_REGISTER_PENDING";
export const EMAIL_REGISTER_SUCCESS = "EMAIL_REGISTER_SUCCESS";
export const EMAIL_REGISTER_ERROR = "EMAIL_REGISTER_ERROR";

export const EMAIL_LOGIN_PENDING = "EMAIL_LOGIN_PENDING";
export const EMAIL_LOGIN_SUCCESS = "EMAIL_LOGIN_SUCCESS";
export const EMAIL_LOGIN_ERROR = "EMAIL_LOGIN_ERROR";

export const GOOGLE_LOGIN_PENDING = "GOOGLE_LOGIN_PENDING";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_ERROR = "GOOGLE_LOGIN_ERROR";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

// product
export const GET_PRODUCT_LIST_PENDING = "GET_PRODUCT_LIST_PENDING";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_ERROR = "GET_PRODUCT_LIST_ERROR";

export const GET_PRODUCT_DETAIL_PENDING = "GET_PRODUCT_DETAIL_PENDING";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_PRODUCT_DETAIL_ERROR = "GET_PRODUCT_DETAIL_ERROR";
